export const FETCH_QUESTIONS = 'Quizy/Quiz/FETCH_QUESTIONS'
export const FETCH_QUESTIONS_PENDING = 'Quizy/Quiz/FETCH_QUESTIONS_PENDING'
export const FETCH_QUESTIONS_FULFILLED = 'Quizy/Quiz/FETCH_QUESTIONS_FULFILLED'
export const FETCH_QUESTIONS_REJECTED = 'Quizy/Quiz/FETCH_QUESTIONS_REJECTED'

export const ANSWER_QUESTION = 'Quizy/Quiz/ANSWER_QUESTION'

export const CLEAR_QUESTIONS = 'Quizy/Quiz/CLEAR_QUESTIONS'
